title: Decidim Awesome Docs
description: Decidim Awesome Docs site.

# https://pmarsceill.github.io/just-the-docs/docs/configuration/
#
# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/just-the-docs.png"

search_enabled: true

remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Platoniq":
    - "//platoniq.net"


# defaults:
#   - scope:
#       type: pages
#     values:
#       layout: "default"
